version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb+srv://ukikalix:NFkIV3AWTVytQQhU@task-db.wbxri.mongodb.net/?retryWrites=true&w=majority&appName=task-db
      